# Generated by Django 4.1.2 on 2023-03-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(max_length=2022),
        ),
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(max_length=2044),
        ),
    ]
