# Generated by Django 4.1.2 on 2023-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_stripe_charge_id_payment_paystack_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_type",
        ),
        migrations.AddField(
            model_name="address",
            name="phone_number",
            field=models.CharField(default="provide for each", max_length=200),
            preserve_default=False,
        ),
    ]
