# Generated by Django 4.1.2 on 2023-06-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_address_country_alter_order_being_delivered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="preview4",
        ),
        migrations.RemoveField(
            model_name="item",
            name="preview_video",
        ),
        migrations.AlterField(
            model_name="item",
            name="sales_category",
            field=models.CharField(
                choices=[
                    ("Hand-fans", "Hand-fans"),
                    ("Laptop-bags", "Laptop-bags"),
                    ("Kimono-and-fabric", "Kimono-and-fabric"),
                    ("Ipad-bag", "Ipad-bag"),
                    ("Woven-bags", "Woven-bags"),
                    ("Bible-bags", "Bible-bags"),
                    ("Beads-work", "Beads-work"),
                    ("Wallets", "Wallets"),
                    ("Slippers", "Slippers"),
                ],
                max_length=20,
            ),
        ),
    ]
