# Generated by Django 4.2.3 on 2023-08-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_item_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="being_delivered",
        ),
        migrations.RemoveField(
            model_name="order",
            name="received",
        ),
        migrations.RemoveField(
            model_name="order",
            name="refund_granted",
        ),
        migrations.RemoveField(
            model_name="order",
            name="refund_requested",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("C", "Cart"),
                    ("B", "Billing Address Added"),
                    ("P", "Payment Processing"),
                    ("D", "Being Delivered"),
                    ("R", "Received"),
                    ("F", "Refunded"),
                ],
                default="C",
                max_length=1,
            ),
        ),
    ]
