# Generated by Django 4.2.3 on 2023-08-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_order_being_delivered_remove_order_received_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Hand fans", "Hand fans"),
                            ("Laptop bags", "Laptop bags"),
                            ("Kimono and fabric", "Kimono and fabric"),
                            ("Ipad bag", "Ipad bag"),
                            ("Woven bags", "Woven bags"),
                            ("Bible bags", "Bible bags"),
                            ("Beads work", "Beads work"),
                            ("Wallets", "Wallets"),
                            ("Slippers", "Slippers"),
                        ],
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(max_length=2044)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
