# Generated by Django 4.2.3 on 2023-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_header_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="header",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Furniture", "Furniture"),
                    ("Watches", "Watches"),
                    ("Shoes", "Shoes"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Furniture", "Furniture"),
                    ("Watches", "Watches"),
                    ("Shoes", "Shoes"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="label",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Furniture", "Furniture"),
                    ("Watches", "Watches"),
                    ("Shoes", "Shoes"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="sales_category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Furniture", "Furniture"),
                    ("Watches", "Watches"),
                    ("Shoes", "Shoes"),
                ],
                max_length=20,
            ),
        ),
    ]
