# Generated by Django 4.2.3 on 2024-01-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_header_category_alter_item_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                ("image2", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
            ],
        ),
    ]
